apiVersion: v1
kind: Service
metadata:
  name: patient-app-service
spec:
  type: NodePort
  selector:
    app: patient-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080  # تدخل عليه من المتصفح
